'use client'

import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { getAllUsers, getCPMRate, promoteUserToAdmin, updateCPMRate, verifyOwnerKey } from '@/app/actions/links'
import { ArrowDownRight, ArrowUpRight, Ban, Check, ChevronRight, CircleDollarSign, Headphones, KeyRound, LayoutDashboard, LockKeyhole, Megaphone, MoreHorizontal, Power, Search, Send, Settings2, ShieldAlert, SlidersHorizontal, UserRound, WalletCards, X } from 'lucide-react'

const tabs = [
  { id: 'treasury', label: 'Treasury', icon: WalletCards },
  { id: 'rates', label: 'Country CPM', icon: SlidersHorizontal },
  { id: 'support', label: 'Support Inbox', icon: Headphones },
  { id: 'users', label: 'Users', icon: UserRound },
  { id: 'settings', label: 'System settings', icon: Settings2 },
  { id: 'shield', label: 'Traffic shield', icon: ShieldAlert },
] as const

type TabId = (typeof tabs)[number]['id']
type User = { id: string; name: string; email: string; role: string; totalClicks: number; totalRevenue: number }
type Rate = { code: string; name: string; ecpm: string; fallback?: boolean }

const seedRates: Rate[] = [
  { code: 'US', name: 'United States', ecpm: '10.00' },
  { code: 'GB', name: 'United Kingdom', ecpm: '8.00' },
  { code: 'PK', name: 'Pakistan', ecpm: '1.50' },
  { code: 'IN', name: 'India', ecpm: '1.20' },
  { code: 'XX', name: 'Global fallback', ecpm: '1.00', fallback: true },
]

function Metric({ label, value, detail, tone = 'blue' }: { label: string; value: string; detail: string; tone?: 'blue' | 'green' | 'amber' }) {
  return <div className="rounded-2xl border border-white/10 bg-white/[0.045] p-5"><div className="flex items-start justify-between gap-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/45">{label}</p><span className={`rounded-full p-2 ${tone === 'green' ? 'bg-emerald-400/10 text-emerald-300' : tone === 'amber' ? 'bg-amber-300/10 text-amber-200' : 'bg-blue-400/10 text-blue-300'}`}><CircleDollarSign className="size-4" /></span></div><p className="mt-5 text-3xl font-semibold tracking-tight text-white">{value}</p><p className="mt-2 text-xs text-white/40">{detail}</p></div>
}

function EmptyState({ title, message }: { title: string; message: string }) {
  return <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.02] px-6 py-12 text-center"><p className="font-medium text-white/75">{title}</p><p className="mt-2 text-sm text-white/40">{message}</p></div>
}

export default function OwnerPage() {
  const [key, setKey] = useState('')
  const [unlocked, setUnlocked] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [activeTab, setActiveTab] = useState<TabId>('treasury')
  const [users, setUsers] = useState<User[]>([])
  const [search, setSearch] = useState('')
  const [rates, setRates] = useState(seedRates)
  const [minimumPayout, setMinimumPayout] = useState('10.00')
  const [maintenance, setMaintenance] = useState(false)
  const [announcement, setAnnouncement] = useState('')
  const [gateways, setGateways] = useState({ JazzCash: true, EasyPaisa: true, Bank: true, Crypto: false })
  const [shields, setShields] = useState({ vpn: true, adblock: true, dedup: true })
  const [dedupWindow, setDedupWindow] = useState('24 hours')
  const [saved, setSaved] = useState('')
  const [selectedTicket, setSelectedTicket] = useState<string | null>(null)
  const [reply, setReply] = useState('')
  const [selectedUser, setSelectedUser] = useState<User | null>(null)
  const [adjustment, setAdjustment] = useState('')
  const [auditNote, setAuditNote] = useState('')

  async function unlock() {
    setBusy(true); setError('')
    const result = await verifyOwnerKey(key)
    if (!result.ok) setError('That owner key was not accepted.')
    else { setUnlocked(true); setUsers((await getAllUsers()) ?? []) }
    setBusy(false)
  }

  async function saveRate() {
    const result = await updateCPMRate(Number(rates.find((rate) => rate.fallback)?.ecpm ?? 1))
    setSaved(result.ok ? 'Rate settings saved.' : result.error ?? 'Could not save rate settings.')
  }

  const filteredUsers = useMemo(() => users.filter((user) => `${user.name} ${user.email} ${user.id}`.toLowerCase().includes(search.toLowerCase())), [users, search])

  if (!unlocked) return <main className="flex min-h-dvh items-center justify-center bg-[#080b12] px-5 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#101622] p-7 shadow-2xl shadow-black/40"><div className="flex size-12 items-center justify-center rounded-2xl bg-blue-400/10 text-blue-300"><KeyRound className="size-5" /></div><p className="mt-7 text-xs font-bold tracking-[0.22em] text-blue-300">SNIPLINK / OWNER ACCESS</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Remote command center</h1><p className="mt-2 text-sm leading-6 text-white/45">Unlock the private operations workspace for treasury, support, and traffic controls.</p><input aria-label="Owner secret key" type="password" value={key} onChange={(event) => setKey(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.nativeEvent.isComposing && event.keyCode !== 229) unlock() }} placeholder="Owner secret key" className="mt-7 h-12 w-full rounded-xl border border-white/10 bg-black/20 px-4 text-sm outline-none transition focus:border-blue-400/60" />{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<Button onClick={unlock} disabled={busy || !key} className="mt-4 h-12 w-full bg-blue-500 text-white hover:bg-blue-400">{busy ? 'Verifying access…' : 'Unlock control room'}<ChevronRight data-icon="inline-end" /></Button></div></main>

  return <main className="min-h-dvh bg-[#080b12] text-white"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 px-4 py-5 sm:px-8 lg:flex-row lg:px-10 lg:py-8"><aside className="lg:sticky lg:top-8 lg:h-[calc(100dvh-4rem)] lg:w-64 lg:shrink-0"><div className="flex items-center gap-3 border-b border-white/10 pb-5"><div className="flex size-10 items-center justify-center rounded-xl bg-blue-500 text-white"><LockKeyhole className="size-5" /></div><div><p className="font-semibold">Sniplink</p><p className="text-xs text-white/40">Owner workspace</p></div></div><nav className="mt-6 grid grid-cols-2 gap-2 lg:grid-cols-1" aria-label="Owner command center tabs">{tabs.map((tab) => { const Icon = tab.icon; const active = activeTab === tab.id; return <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex cursor-pointer select-none items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${active ? 'bg-blue-500 text-white shadow-lg shadow-blue-500/20' : 'text-white/50 hover:bg-white/5 hover:text-white'}`}><Icon className="size-4" />{tab.label}{tab.id === 'support' && <span className="ml-auto rounded-full bg-amber-300 px-2 py-0.5 text-[10px] font-bold text-slate-950">3</span>}</button> })}</nav><div className="mt-8 hidden rounded-2xl border border-white/10 bg-white/[0.035] p-4 lg:block"><p className="text-xs uppercase tracking-[0.16em] text-white/35">System status</p><div className="mt-4 flex items-center gap-2 text-sm"><span className="size-2 rounded-full bg-emerald-400" />All services operational</div><p className="mt-2 text-xs text-white/35">Last synced just now</p></div></aside><section className="min-w-0 flex-1"><header className="flex flex-col justify-between gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[0.2em] text-blue-300">OWNER CONTROL ROOM</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{tabs.find((tab) => tab.id === activeTab)?.label}</h1><p className="mt-2 text-sm text-white/40">Manage the platform from one secure workspace.</p></div><div className="flex items-center gap-2 text-xs text-emerald-300"><span className="size-2 rounded-full bg-emerald-400" />Live connection</div></header>

{activeTab === 'treasury' && <div className="mt-7 flex flex-col gap-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Gross earnings" value="$0.00" detail="Estimated platform revenue" /><Metric label="User liabilities" value="$0.00" detail="Available publisher balances" tone="amber" /><Metric label="Net owner profit" value="$0.00" detail="Current treasury margin" tone="green" /><Metric label="Pending withdrawals" value="0" detail="Awaiting review" /></div><div className="rounded-2xl border border-white/10 bg-[#101622] p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-300">Withdrawal approval engine</p><h2 className="mt-2 text-xl font-semibold">Payout queue</h2></div><Button variant="outline" className="border-white/10 bg-white/5 text-white hover:bg-white/10">Export ledger</Button></div><div className="mt-6"><EmptyState title="No pending withdrawals" message="Approved payout requests will appear here for review." /></div></div></div>}

{activeTab === 'rates' && <div className="mt-7 flex flex-col gap-6"><div className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4 text-sm text-amber-100"><p className="font-semibold">Confidential rate manager</p><p className="mt-1 text-amber-100/60">These internal base rates are used to lock historical view earnings. Publisher surfaces show only their final published rate.</p></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#101622]"><div className="flex flex-col justify-between gap-4 border-b border-white/10 p-5 sm:flex-row sm:items-center"><div><h2 className="font-semibold">Country rates</h2><p className="mt-1 text-sm text-white/40">Update rates without changing completed views.</p></div><Button onClick={saveRate} className="bg-blue-500 text-white hover:bg-blue-400">Save changes</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-wider text-white/35"><tr><th className="px-5 py-4">Country</th><th className="px-5 py-4">Code</th><th className="px-5 py-4">Base eCPM</th><th className="px-5 py-4">Type</th></tr></thead><tbody>{rates.map((rate, index) => <tr key={rate.code} className="border-t border-white/10"><td className="px-5 py-4 font-medium">{rate.name}</td><td className="px-5 py-4 font-mono text-white/50">{rate.code}</td><td className="px-5 py-3"><div className="flex max-w-[160px] items-center rounded-lg border border-white/10 bg-black/20 px-3"><span className="text-white/35">$</span><input aria-label={`${rate.code} eCPM`} value={rate.ecpm} onChange={(event) => setRates((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ecpm: event.target.value } : item))} className="h-9 w-full bg-transparent px-2 outline-none" /></div></td><td className="px-5 py-4">{rate.fallback ? <span className="rounded-full bg-blue-400/10 px-2.5 py-1 text-xs text-blue-200">Fallback</span> : <span className="text-white/35">Country</span>}</td></tr>)}</tbody></table></div></div>{saved && <p className="text-sm text-emerald-300">{saved}</p>}</div>}

{activeTab === 'support' && <div className="mt-7 rounded-2xl border border-white/10 bg-[#101622] p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Support inbox</h2><p className="mt-1 text-sm text-white/40">Respond to publisher conversations.</p></div><span className="rounded-full bg-amber-300 px-3 py-1 text-xs font-bold text-slate-950">3 unread</span></div><div className="mt-6 grid gap-3">{['Payment method verification', 'My clicks are not showing', 'Account review request'].map((ticket, index) => <button key={ticket} type="button" onClick={() => setSelectedTicket(ticket)} className="flex cursor-pointer select-none items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/[0.03] p-4 text-left transition hover:border-blue-400/40 hover:bg-white/[0.06]"><div><p className="font-medium">{ticket}</p><p className="mt-1 text-xs text-white/35">publisher-{index + 1}@example.com · 12 min ago</p></div><span className={`rounded-full px-2.5 py-1 text-xs ${index === 0 ? 'bg-blue-400/10 text-blue-200' : 'bg-amber-300/10 text-amber-200'}`}>{index === 0 ? 'Replied' : 'Open'}</span></button>)}</div></div>}

{activeTab === 'users' && <div className="mt-7 flex flex-col gap-6"><div className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#101622] px-4"><Search className="size-4 text-white/35" /><input aria-label="Search users" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name, email, or ID" className="h-12 flex-1 bg-transparent text-sm outline-none" /></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#101622]"><div className="border-b border-white/10 p-5"><h2 className="font-semibold">User master directory</h2><p className="mt-1 text-sm text-white/40">{filteredUsers.length} accounts available</p></div>{filteredUsers.length ? <div className="divide-y divide-white/10">{filteredUsers.map((user) => <div key={user.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{user.name}</p><p className="mt-1 text-sm text-white/40">{user.email} · {user.totalClicks} clicks · ${user.totalRevenue.toFixed(2)}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setSelectedUser(user)} className="border-white/10 bg-white/5 text-white hover:bg-white/10">Adjust balance</Button><Button size="sm" variant="outline" className="border-red-300/20 bg-red-300/5 text-red-200 hover:bg-red-300/10"><Ban data-icon="inline-start" />Ban</Button></div></div>)}</div> : <div className="p-5"><EmptyState title="No users loaded" message="Unlock access with an owner key to load the live directory." /></div>}</div></div>}

{activeTab === 'settings' && <div className="mt-7 grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#101622] p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Platform status</h2><p className="mt-1 text-sm text-white/40">Pause public traffic while you deploy changes.</p></div><button type="button" aria-pressed={maintenance} onClick={() => setMaintenance(!maintenance)} className={`relative h-7 w-12 cursor-pointer select-none rounded-full transition ${maintenance ? 'bg-blue-500' : 'bg-white/15'}`}><span className={`absolute top-1 size-5 rounded-full bg-white transition ${maintenance ? 'left-6' : 'left-1'}`} /></button></div><label className="mt-7 block text-sm font-medium text-white/70">Maintenance message<textarea value={announcement} onChange={(event) => setAnnouncement(event.target.value)} placeholder="Scheduled maintenance notice…" className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none focus:border-blue-400/60" /></label><Button className="mt-4 bg-blue-500 text-white hover:bg-blue-400" onClick={() => setSaved('System settings published.')}>Publish settings</Button></div><div className="rounded-2xl border border-white/10 bg-[#101622] p-5 sm:p-7"><h2 className="font-semibold">Payout rules</h2><p className="mt-1 text-sm text-white/40">Set the minimum eligible withdrawal amount.</p><label className="mt-6 block text-sm text-white/70">Minimum withdrawal<div className="mt-2 flex items-center rounded-xl border border-white/10 bg-black/20 px-3"><span className="text-white/35">$</span><input value={minimumPayout} onChange={(event) => setMinimumPayout(event.target.value)} className="h-11 w-full bg-transparent px-2 outline-none" /></div></label><div className="mt-7 border-t border-white/10 pt-5"><p className="text-sm font-medium">Payment gateways</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(gateways).map(([name, enabled]) => <button type="button" key={name} onClick={() => setGateways((items) => ({ ...items, [name]: !enabled }))} className="flex cursor-pointer select-none items-center justify-between rounded-xl border border-white/10 bg-white/[0.03] px-3 py-3 text-left text-sm"><span>{name}</span><span className={`size-2 rounded-full ${enabled ? 'bg-emerald-400' : 'bg-white/20'}`} /></button>)}</div></div></div></div>}

{activeTab === 'shield' && <div className="mt-7 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><div className="rounded-2xl border border-white/10 bg-[#101622] p-5 sm:p-7"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-300">Traffic controls</p><h2 className="mt-2 text-xl font-semibold">Anti-fraud shield</h2><p className="mt-2 text-sm text-white/40">Control enforcement before suspicious traffic becomes a payout liability.</p></div><div className="mt-7 divide-y divide-white/10">{[['vpn', 'VPN / proxy blocking', 'Flag known datacenter and proxy traffic.'], ['adblock', 'AdBlocker enforcement', 'Require the interstitial ad step to complete.'], ['dedup', 'IP deduplication', 'Ignore repeat views from one IP during the window.']].map(([id, label, description]) => <div key={id} className="flex items-center justify-between gap-5 py-5"><div><p className="font-medium">{label}</p><p className="mt-1 text-sm text-white/40">{description}</p></div><button type="button" aria-pressed={shields[id as keyof typeof shields]} onClick={() => setShields((items) => ({ ...items, [id]: !items[id as keyof typeof shields] }))} className={`relative h-7 w-12 cursor-pointer select-none rounded-full transition ${shields[id as keyof typeof shields] ? 'bg-blue-500' : 'bg-white/15'}`}><span className={`absolute top-1 size-5 rounded-full bg-white transition ${shields[id as keyof typeof shields] ? 'left-6' : 'left-1'}`} /></button></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-3 border-t border-white/10 pt-5"><label className="text-sm text-white/60">Deduplication window</label><select value={dedupWindow} onChange={(event) => setDedupWindow(event.target.value)} className="cursor-pointer rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm"><option>12 hours</option><option>24 hours</option></select></div></div><div className="rounded-2xl border border-white/10 bg-[#101622] p-5 sm:p-7"><div className="flex items-center gap-3"><ShieldAlert className="size-5 text-amber-200" /><h2 className="font-semibold">Audit log</h2></div><div className="mt-6"><EmptyState title="No suspicious activity" message="Flagged IPs and proxy attempts will appear here." /></div></div></div>}

</section></div>{selectedTicket && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 sm:items-center"><div className="w-full max-w-xl rounded-2xl border border-white/10 bg-[#101622] p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-blue-300">Support ticket</p><h2 className="mt-2 text-xl font-semibold">{selectedTicket}</h2></div><button type="button" onClick={() => setSelectedTicket(null)} className="cursor-pointer rounded-lg p-2 text-white/50 hover:bg-white/10 hover:text-white"><X /></button></div><div className="mt-6 rounded-xl bg-white/[0.04] p-4 text-sm text-white/65">Hello, I need help with this request. Please review my account and let me know the next step.</div><div className="mt-4 flex gap-2"><input aria-label="Reply to ticket" value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply…" className="h-11 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none" /><Button onClick={() => { setReply(''); setSelectedTicket(null); setSaved('Reply sent.') }} className="bg-blue-500 text-white hover:bg-blue-400"><Send /></Button></div></div></div>}{selectedUser && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 sm:items-center"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#101622] p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-widest text-blue-300">Balance override</p><h2 className="mt-2 text-xl font-semibold">{selectedUser.email}</h2></div><button type="button" onClick={() => setSelectedUser(null)} className="cursor-pointer rounded-lg p-2 text-white/50 hover:bg-white/10"><X /></button></div><label className="mt-6 block text-sm text-white/60">Amount<div className="mt-2 flex items-center rounded-xl border border-white/10 bg-black/20 px-3"><span className="text-white/35">$</span><input value={adjustment} onChange={(event) => setAdjustment(event.target.value)} placeholder="+5.00 or -2.00" className="h-11 w-full bg-transparent px-2 outline-none" /></div></label><label className="mt-4 block text-sm text-white/60">Required audit note<textarea value={auditNote} onChange={(event) => setAuditNote(event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none" placeholder="Reason for this adjustment" /></label><Button disabled={!adjustment || !auditNote} onClick={() => { setSelectedUser(null); setAdjustment(''); setAuditNote(''); setSaved('Balance adjustment recorded.') }} className="mt-4 w-full bg-blue-500 text-white hover:bg-blue-400">Record adjustment</Button></div></div>}{saved && <div className="fixed bottom-5 right-5 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-200 shadow-xl">{saved}</div>}</main>
}
