import type React from 'react'
import { auth } from '@/lib/auth'
import { headers } from 'next/headers'
import { ArrowRight, BarChart3, Check, ChevronRight, Eye, Link2, Menu, ShieldCheck, Sparkles, Wallet } from 'lucide-react'
import { ShortenerForm } from '@/components/shortener-form'

export default async function HomePage() {
  const session = await auth.api.getSession({ headers: await headers() })
  return (
    <main className="min-h-dvh overflow-hidden bg-[#f8f9ff] text-[#12162d]">
      <header className="sticky top-0 z-20 border-b border-[#dfe3f0]/80 bg-[#f8f9ff]/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8">
          <a href="/" className="flex items-center gap-3" aria-label="Sniplink home"><span className="flex size-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-600 to-cyan-500 text-white shadow-lg shadow-violet-500/20"><Link2 className="size-5" /></span><span className="text-xl font-extrabold tracking-[-0.04em]">Snip<span className="text-violet-600">link</span></span></a>
          <nav className="hidden items-center gap-8 text-sm font-semibold text-[#68708a] md:flex"><a href="#how-it-works" className="hover:text-[#12162d]">How it works</a><a href="#features" className="hover:text-[#12162d]">Features</a><a href="#rates" className="hover:text-[#12162d]">Rates</a></nav>
          <div className="flex items-center gap-3">{session ? <a href="/dashboard" className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-violet-600/20">Open dashboard</a> : <><a href="/sign-in" className="hidden text-sm font-bold text-[#68708a] sm:block">Sign in</a><a href="/sign-up" className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-violet-600/20">Start earning</a></>}<button className="rounded-xl border border-[#dfe3f0] bg-white p-2.5 md:hidden" aria-label="Open menu"><Menu className="size-5" /></button></div>
        </div>
      </header>
      <section className="mx-auto max-w-7xl px-5 pb-20 pt-16 sm:px-8 sm:pt-24"><div className="mx-auto max-w-4xl text-center"><div className="inline-flex items-center gap-2 rounded-full border border-cyan-300 bg-cyan-50 px-4 py-2 text-xs font-bold text-cyan-700"><ShieldCheck className="size-4" /> Transparent creator earnings</div><h1 className="mt-7 text-5xl font-black leading-[0.98] tracking-[-0.065em] sm:text-7xl lg:text-8xl">Every click,<br /><span className="bg-gradient-to-r from-violet-600 via-fuchsia-500 to-cyan-500 bg-clip-text text-transparent">made meaningful.</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-[#68708a] sm:text-xl">Shorten your links, grow your audience, and earn from qualified views with a clear dashboard built for creators.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><a href={session ? '/dashboard' : '/sign-up'} className="inline-flex h-14 items-center justify-center gap-3 rounded-2xl bg-violet-600 px-8 text-base font-bold text-white shadow-xl shadow-violet-600/25">{session ? 'Open dashboard' : 'Start earning free'} <ArrowRight className="size-5" /></a><a href="#how-it-works" className="inline-flex h-14 items-center justify-center rounded-2xl border border-[#dfe3f0] bg-white px-8 text-base font-bold shadow-sm">See how it works</a></div></div><div className="mx-auto mt-16 max-w-5xl rounded-[2rem] border border-[#dfe3f0] bg-white p-4 shadow-2xl shadow-violet-900/10 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="size-3 rounded-full bg-rose-400" /><span className="size-3 rounded-full bg-amber-400" /><span className="size-3 rounded-full bg-emerald-400" /><span className="ml-3 text-xs font-bold tracking-[0.18em] text-[#9ba3ba]">SNIPLINK WORKSPACE</span></div><ShortenerForm /></div></section>
      <section id="how-it-works" className="border-y border-[#e5e8f2] bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-sm font-black uppercase tracking-[0.2em] text-violet-600">Simple by design</p><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] sm:text-6xl">A better link flow.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3"><Step number="01" icon={<Link2 />} title="Shorten a link" copy="Paste any destination and get a clean Sniplink URL in seconds." /><Step number="02" icon={<Eye />} title="Visitors click" copy="A transparent, branded interstitial gives every visitor a consistent experience." /><Step number="03" icon={<Wallet />} title="Watch earnings grow" copy="Qualified views convert into earnings you can track and withdraw." /></div></div></section>
      <section id="features" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><Feature icon={<BarChart3 />} title="Live analytics" copy="See clicks, reach, and performance without guesswork." /><Feature icon={<ShieldCheck />} title="Built for trust" copy="Clear rates, protected accounts, and visible payout history." /><Feature icon={<Sparkles />} title="Creator-first" copy="A polished workflow that keeps your audience moving." /><Feature icon={<Check />} title="Fast payouts" copy="Submit withdrawals once your available balance reaches $5." /></div></section>
      <footer className="border-t border-[#e5e8f2] bg-white px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-[#68708a] sm:flex-row"><span className="font-bold text-[#12162d]">Sniplink</span><span>Short links with a clearer destination.</span><a href="/owner-control-2f9x" className="hover:text-violet-600">Owner portal</a></div></footer>
    </main>
  )
}
function Step({ number, icon, title, copy }: { number: string; icon: React.ReactNode; title: string; copy: string }) { return <article className="rounded-[2rem] border border-[#dfe3f0] bg-[#f8f9ff] p-7"><div className="flex items-center justify-between"><span className="flex size-14 items-center justify-center rounded-2xl bg-violet-100 text-violet-600">{icon}</span><span className="text-3xl font-black text-[#d5d9e6]">{number}</span></div><h3 className="mt-10 text-2xl font-black tracking-[-0.04em]">{title}</h3><p className="mt-3 leading-7 text-[#68708a]">{copy}</p><ChevronRight className="mt-6 size-5 text-violet-600" /></article> }
function Feature({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <article className="rounded-3xl border border-[#dfe3f0] bg-white p-6 shadow-sm"><div className="flex size-11 items-center justify-center rounded-2xl bg-cyan-50 text-cyan-600">{icon}</div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[#68708a]">{copy}</p></article> }
