'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { getAllUsers, promoteUserToAdmin, updateCPMRate, verifyOwnerKey } from '@/app/actions/links'
import { KeyRound, Loader2, ShieldCheck, UserPlus } from 'lucide-react'

type OwnerUser = { id: string; name: string; email: string; role: string; totalClicks: number; totalRevenue: number }
export function OwnerConsole({ initialUsers, currentRate }: { initialUsers: OwnerUser[]; currentRate: number }) {
  const [key, setKey] = useState(''); const [unlocked, setUnlocked] = useState(false); const [error, setError] = useState(''); const [rate, setRate] = useState(String(currentRate)); const [pending, setPending] = useState(false); const [users, setUsers] = useState(initialUsers)
  async function unlock() { setPending(true); const result = await verifyOwnerKey(key); if (!result.ok) setError('That owner key was not accepted.'); else { setUsers((await getAllUsers()) ?? []); setUnlocked(true) }; setPending(false) }
  async function makeAdmin(id: string) { setPending(true); const result = await promoteUserToAdmin(id); if (result.ok) setUsers((items) => items.map((item) => item.id === id ? { ...item, role: 'admin' } : item)); else setError(result.error ?? 'Could not update user.'); setPending(false) }
  async function saveRate() { const result = await updateCPMRate(Number(rate)); if (!result.ok) setError(result.error ?? 'Could not save rate.') }
  if (!unlocked) return <main className="flex min-h-dvh items-center justify-center px-5"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-7 shadow-2xl"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><KeyRound className="size-5" /></div><p className="mt-7 text-sm font-bold tracking-[0.2em] text-primary">OWNER CONSOLE</p><h1 className="mt-3 text-3xl font-bold">Private control room</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Manage platform access and payout settings.</p><input type="password" value={key} onChange={(e) => setKey(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) unlock() }} className="mt-7 h-12 w-full rounded-xl border border-border bg-background px-4" placeholder="Owner secret key" />{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}<Button onClick={unlock} disabled={pending || !key} className="mt-4 h-12 w-full">{pending ? <Loader2 className="animate-spin" /> : 'Unlock console'}</Button></div></main>
  return <main className="min-h-dvh px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><header><p className="text-sm font-bold tracking-[0.2em] text-primary">OWNER CONSOLE</p><h1 className="mt-2 text-3xl font-bold">Control room</h1></header><div className="mt-10 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><section className="rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-primary" /><h2 className="font-bold">Publisher CPM</h2></div><p className="mt-3 text-sm text-muted-foreground">Payout per 1,000 valid completed views.</p><div className="mt-6 flex gap-3"><input type="number" min="0" step="0.01" value={rate} onChange={(e) => setRate(e.target.value)} className="h-11 min-w-0 flex-1 rounded-xl border border-border bg-background px-3" /><Button onClick={saveRate}>Save CPM</Button></div></section><section className="rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><UserPlus className="size-5 text-primary" /><h2 className="font-bold">Administrators</h2></div><div className="mt-5 divide-y divide-border">{users.map((item) => <div key={item.id} className="flex select-none items-center justify-between gap-3 py-4"><div><p className="font-semibold">{item.name}</p><p className="text-sm text-muted-foreground">{item.email}</p></div>{item.role === 'admin' ? <span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-600">Admin</span> : <Button size="sm" variant="outline" onClick={() => makeAdmin(item.id)} disabled={pending}>Make admin</Button>}</div>)}</div></section></div><a className="mt-8 inline-flex cursor-pointer select-none rounded-xl px-3 py-2 text-sm font-semibold text-primary hover:bg-primary/10" href="/admin/withdrawals">Open withdrawal management</a></div></main>
}
